# Generated by Django 5.2.13 on 2026-04-09 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('photo_url', models.URLField(blank=True, help_text='Link to uploaded photo', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PilatesClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_time', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(default=50)),
                ('capacity', models.IntegerField(default=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='studio.instructor')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_email', models.EmailField(max_length=254)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pilates_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='studio.pilatesclass')),
            ],
        ),
    ]
