# Generated by Django 5.2.13 on 2026-04-09 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pilatesclass',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
